version: 2
updates:
  - package-ecosystem: gradle
    directory: 'codegen'
    schedule:
      interval: weekly
      time: '06:00'
      timezone: 'Europe/Amsterdam'
    labels:
      - dependencies
    reviewers:
      - "msrd0"
  
  - package-ecosystem: gradle
    directory: 'fontawesome'
    schedule:
      interval: weekly
      time: '06:00'
      timezone: 'Europe/Amsterdam'
    labels:
      - dependencies
    reviewers:
      - "msrd0"
